//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaspberryConteiner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaspberryConteiner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataBase Error.
        /// </summary>
        internal static string Device_CreateStatsAsync_DataBase_Error {
            get {
                return ResourceManager.GetString("Device_CreateStatsAsync_DataBase_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is empty.
        /// </summary>
        internal static string Device_SetTemp_The_field_is_empty {
            get {
                return ResourceManager.GetString("Device_SetTemp_The_field_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error database.
        /// </summary>
        internal static string Device_StartGettingTemp_Error_database {
            get {
                return ResourceManager.GetString("Device_StartGettingTemp_Error_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set max temperature.
        /// </summary>
        internal static string Device_StartGettingTemp_Set_max_temperature {
            get {
                return ResourceManager.GetString("Device_StartGettingTemp_Set_max_temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device Added!.
        /// </summary>
        internal static string MainWindow_Button_Click_New_Device_Added_ {
            get {
                return ResourceManager.GetString("MainWindow_Button_Click_New_Device_Added_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MainWindow_Error {
            get {
                return ResourceManager.GetString("MainWindow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding new device.
        /// </summary>
        internal static string MainWindow_Error_adding_new_device {
            get {
                return ResourceManager.GetString("MainWindow_Error_adding_new_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error export data.
        /// </summary>
        internal static string MainWindow_Error_export_data {
            get {
                return ResourceManager.GetString("MainWindow_Error_export_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error server.
        /// </summary>
        internal static string MainWindow_Error_server {
            get {
                return ResourceManager.GetString("MainWindow_Error_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        internal static string MainWindow_Export_data {
            get {
                return ResourceManager.GetString("MainWindow_Export_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MainWindow_Information {
            get {
                return ResourceManager.GetString("MainWindow_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Added!.
        /// </summary>
        internal static string MainWindow_New_User_Added_ {
            get {
                return ResourceManager.GetString("MainWindow_New_User_Added_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved!.
        /// </summary>
        internal static string MainWindow_Settings_saved_ {
            get {
                return ResourceManager.GetString("MainWindow_Settings_saved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics is empty.
        /// </summary>
        internal static string MainWindow_Statistics_is_empty {
            get {
                return ResourceManager.GetString("MainWindow_Statistics_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name is empty.
        /// </summary>
        internal static string MainWindow_The_Name_is_empty {
            get {
                return ResourceManager.GetString("MainWindow_The_Name_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number Platform is empty.
        /// </summary>
        internal static string MainWindow_The_Number_Platform_is_empty {
            get {
                return ResourceManager.GetString("MainWindow_The_Number_Platform_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exists in the database..
        /// </summary>
        internal static string MainWindow_This_name_already_exists_in_the_database_ {
            get {
                return ResourceManager.GetString("MainWindow_This_name_already_exists_in_the_database_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are successfully exported tour Data!.
        /// </summary>
        internal static string MainWindow_You_are_successfully_exported_tour_Data_ {
            get {
                return ResourceManager.GetString("MainWindow_You_are_successfully_exported_tour_Data_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///     Restart the device!.
        /// </summary>
        internal static string UserCard_TestControl_Restart_The_device {
            get {
                return ResourceManager.GetString("UserCard_TestControl_Restart_The_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You changed user on: .
        /// </summary>
        internal static string UserCard_TestControl_You_changed_user_on__ {
            get {
                return ResourceManager.GetString("UserCard_TestControl_You_changed_user_on__", resourceCulture);
            }
        }
    }
}
